#!/bin/sh
#
# Pre-commit hook
#

# Run the Maven verify command
./mvnw verify --offline

# Capture exit status of Maven command
RESULT=$?

# If command failed, abort the commit
if [ $RESULT -ne 0 ]; then
    echo "Git pre-commit verification failed"
    exit 1
fi

# Check for changes made by Spotless
if ! git diff --cached --quiet; then
    echo "Spotless made changes, adding them to the commit..."
    git add .
fi

# If everything is okay, allow the commit to proceed
exit 0
